package cliente_servidores;


/**
* cliente_servidores/_DespachosStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos.idl
* viernes 7 de abril de 2017 12:04:27 AM COT
*/

public class _DespachosStub extends org.omg.CORBA.portable.ObjectImpl implements cliente_servidores.Despachos
{

  public int insertarDespachos (int id_filiales, String nombre_filiales, int id_producto, String descripcion_producto, int id_conductor, String nombre_conductor, String direccion_despacho, String fecha_salida, String hora_salida, String fecha_llegada, String hora_llegada, String peso_mercancia, String autorizo, String fecha_creacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarDespachos", true);
                $out.write_long (id_filiales);
                $out.write_wstring (nombre_filiales);
                $out.write_long (id_producto);
                $out.write_wstring (descripcion_producto);
                $out.write_long (id_conductor);
                $out.write_wstring (nombre_conductor);
                $out.write_wstring (direccion_despacho);
                $out.write_wstring (fecha_salida);
                $out.write_wstring (hora_salida);
                $out.write_wstring (fecha_llegada);
                $out.write_wstring (hora_llegada);
                $out.write_wstring (peso_mercancia);
                $out.write_wstring (autorizo);
                $out.write_wstring (fecha_creacion);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarDespachos (id_filiales, nombre_filiales, id_producto, descripcion_producto, id_conductor, nombre_conductor, direccion_despacho, fecha_salida, hora_salida, fecha_llegada, hora_llegada, peso_mercancia, autorizo, fecha_creacion        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarDespachos

  public int insertarFiliales (String nombre, String origen, String ubicacion, String actividad, String fecha_creacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarFiliales", true);
                $out.write_wstring (nombre);
                $out.write_wstring (origen);
                $out.write_wstring (ubicacion);
                $out.write_wstring (actividad);
                $out.write_wstring (fecha_creacion);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarFiliales (nombre, origen, ubicacion, actividad, fecha_creacion        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarFiliales

  public int insertarProductos (String descripcion, int cantidad_stock, String fecha_fabricacion, String fecha_vencimiento, String fecha_creacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarProductos", true);
                $out.write_wstring (descripcion);
                $out.write_long (cantidad_stock);
                $out.write_wstring (fecha_fabricacion);
                $out.write_wstring (fecha_vencimiento);
                $out.write_wstring (fecha_creacion);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarProductos (descripcion, cantidad_stock, fecha_fabricacion, fecha_vencimiento, fecha_creacion        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarProductos

  public int insertarConductores (String nombre_completo, int edad, String direccion, String telefono, String experiencia, String fecha_creacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarConductores", true);
                $out.write_wstring (nombre_completo);
                $out.write_long (edad);
                $out.write_wstring (direccion);
                $out.write_wstring (telefono);
                $out.write_wstring (experiencia);
                $out.write_wstring (fecha_creacion);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarConductores (nombre_completo, edad, direccion, telefono, experiencia, fecha_creacion        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarConductores

  public String consultaFiliales_id (String id_filial)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultaFiliales_id", true);
                $out.write_wstring (id_filial);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultaFiliales_id (id_filial        );
            } finally {
                _releaseReply ($in);
            }
  } // consultaFiliales_id

  public String consultaProductos_id (String id_producto)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultaProductos_id", true);
                $out.write_wstring (id_producto);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultaProductos_id (id_producto        );
            } finally {
                _releaseReply ($in);
            }
  } // consultaProductos_id

  public String consultaConductor_id (String id_conductor)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultaConductor_id", true);
                $out.write_wstring (id_conductor);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultaConductor_id (id_conductor        );
            } finally {
                _releaseReply ($in);
            }
  } // consultaConductor_id

  public int validarUsuarioServidor1 (String usuario, String contrasena)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("validarUsuarioServidor1", true);
                $out.write_wstring (usuario);
                $out.write_wstring (contrasena);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return validarUsuarioServidor1 (usuario, contrasena        );
            } finally {
                _releaseReply ($in);
            }
  } // validarUsuarioServidor1

  public int validarUsuarioServidor2 (String usuario, String contrasena)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("validarUsuarioServidor2", true);
                $out.write_wstring (usuario);
                $out.write_wstring (contrasena);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return validarUsuarioServidor2 (usuario, contrasena        );
            } finally {
                _releaseReply ($in);
            }
  } // validarUsuarioServidor2

  public int validarUsuarioServidor3 (String usuario, String contrasena)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("validarUsuarioServidor3", true);
                $out.write_wstring (usuario);
                $out.write_wstring (contrasena);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return validarUsuarioServidor3 (usuario, contrasena        );
            } finally {
                _releaseReply ($in);
            }
  } // validarUsuarioServidor3

  public int validarUsuarioCliente (String usuario, String contrasena)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("validarUsuarioCliente", true);
                $out.write_wstring (usuario);
                $out.write_wstring (contrasena);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return validarUsuarioCliente (usuario, contrasena        );
            } finally {
                _releaseReply ($in);
            }
  } // validarUsuarioCliente

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cliente_servidores/Despachos:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _DespachosStub
