package cliente_servidores;


/**
* cliente_servidores/DespachosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos.idl
* viernes 7 de abril de 2017 12:04:27 AM COT
*/

public interface DespachosOperations 
{
  int insertarDespachos (int id_filiales, String nombre_filiales, int id_producto, String descripcion_producto, int id_conductor, String nombre_conductor, String direccion_despacho, String fecha_salida, String hora_salida, String fecha_llegada, String hora_llegada, String peso_mercancia, String autorizo, String fecha_creacion);
  int insertarFiliales (String nombre, String origen, String ubicacion, String actividad, String fecha_creacion);
  int insertarProductos (String descripcion, int cantidad_stock, String fecha_fabricacion, String fecha_vencimiento, String fecha_creacion);
  int insertarConductores (String nombre_completo, int edad, String direccion, String telefono, String experiencia, String fecha_creacion);
  String consultaFiliales_id (String id_filial);
  String consultaProductos_id (String id_producto);
  String consultaConductor_id (String id_conductor);
  int validarUsuarioServidor1 (String usuario, String contrasena);
  int validarUsuarioServidor2 (String usuario, String contrasena);
  int validarUsuarioServidor3 (String usuario, String contrasena);
  int validarUsuarioCliente (String usuario, String contrasena);
} // interface DespachosOperations
