package cliente_servidores;


/**
* cliente_servidores/DespachosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos.idl
* viernes 7 de abril de 2017 12:04:27 AM COT
*/

abstract public class DespachosHelper
{
  private static String  _id = "IDL:cliente_servidores/Despachos:1.0";

  public static void insert (org.omg.CORBA.Any a, cliente_servidores.Despachos that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cliente_servidores.Despachos extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (cliente_servidores.DespachosHelper.id (), "Despachos");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cliente_servidores.Despachos read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DespachosStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cliente_servidores.Despachos value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static cliente_servidores.Despachos narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cliente_servidores.Despachos)
      return (cliente_servidores.Despachos)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      cliente_servidores._DespachosStub stub = new cliente_servidores._DespachosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static cliente_servidores.Despachos unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cliente_servidores.Despachos)
      return (cliente_servidores.Despachos)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      cliente_servidores._DespachosStub stub = new cliente_servidores._DespachosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
