package cliente_servidores;

/**
* cliente_servidores/DespachosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos.idl
* viernes 7 de abril de 2017 12:04:27 AM COT
*/

public final class DespachosHolder implements org.omg.CORBA.portable.Streamable
{
  public cliente_servidores.Despachos value = null;

  public DespachosHolder ()
  {
  }

  public DespachosHolder (cliente_servidores.Despachos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cliente_servidores.DespachosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cliente_servidores.DespachosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cliente_servidores.DespachosHelper.type ();
  }

}
