package cliente_servidores;


/**
* cliente_servidores/Despachos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos.idl
* viernes 7 de abril de 2017 12:04:27 AM COT
*/

public interface Despachos extends DespachosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Despachos
