package cliente_servidores2;


/**
* cliente_servidores2/Despachos_Productos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos_Productos.idl
* miércoles 12 de abril de 2017 06:41:12 PM COT
*/

public interface Despachos_Productos extends Despachos_ProductosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Despachos_Productos
