package cliente_servidores2;

/**
* cliente_servidores2/Despachos_ProductosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos_Productos.idl
* miércoles 12 de abril de 2017 06:41:12 PM COT
*/

public final class Despachos_ProductosHolder implements org.omg.CORBA.portable.Streamable
{
  public cliente_servidores2.Despachos_Productos value = null;

  public Despachos_ProductosHolder ()
  {
  }

  public Despachos_ProductosHolder (cliente_servidores2.Despachos_Productos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cliente_servidores2.Despachos_ProductosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cliente_servidores2.Despachos_ProductosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cliente_servidores2.Despachos_ProductosHelper.type ();
  }

}
