package cliente_servidores1;


/**
* cliente_servidores1/Despachos_Filial.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos_Filial.idl
* miércoles 12 de abril de 2017 06:40:33 PM COT
*/

public interface Despachos_Filial extends Despachos_FilialOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Despachos_Filial
