package cliente_servidores1;


/**
* cliente_servidores1/Despachos_FilialOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos_Filial.idl
* miércoles 12 de abril de 2017 06:40:33 PM COT
*/

public interface Despachos_FilialOperations 
{
  int insertarFiliales (String nombre, String origen, String ubicacion, String actividad, String fecha_creacion);
  String consultaFiliales_id (String id_filial);
  int validarUsuarioServidor1 (String usuario, String contrasena);
} // interface Despachos_FilialOperations
