package cliente_servidores3;


/**
* cliente_servidores3/Despachos_Conductor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos_Conductor.idl
* miércoles 12 de abril de 2017 06:41:33 PM COT
*/

public interface Despachos_Conductor extends Despachos_ConductorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Despachos_Conductor
