package cliente_servidores3;


/**
* cliente_servidores3/Despachos_ConductorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Despachos_Conductor.idl
* sábado 22 de abril de 2017 10:46:39 PM COT
*/

abstract public class Despachos_ConductorHelper
{
  private static String  _id = "IDL:cliente_servidores3/Despachos_Conductor:1.0";

  public static void insert (org.omg.CORBA.Any a, cliente_servidores3.Despachos_Conductor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cliente_servidores3.Despachos_Conductor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (cliente_servidores3.Despachos_ConductorHelper.id (), "Despachos_Conductor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cliente_servidores3.Despachos_Conductor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Despachos_ConductorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cliente_servidores3.Despachos_Conductor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static cliente_servidores3.Despachos_Conductor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cliente_servidores3.Despachos_Conductor)
      return (cliente_servidores3.Despachos_Conductor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      cliente_servidores3._Despachos_ConductorStub stub = new cliente_servidores3._Despachos_ConductorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static cliente_servidores3.Despachos_Conductor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cliente_servidores3.Despachos_Conductor)
      return (cliente_servidores3.Despachos_Conductor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      cliente_servidores3._Despachos_ConductorStub stub = new cliente_servidores3._Despachos_ConductorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
